name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x] # Test against multiple Node.js versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        run: npm install --prefix server

      - name: Install client dependencies
        run: npm install --prefix client

    #   - name: Run server lint
    #     run: npm run lint --prefix server

    #   - name: Run client lint
    #     run: npm run lint --prefix client

    #   - name: Run server tests
    #     run: npm test --prefix server

    #   - name: Run client tests
    #     run: npm test --prefix client

      - name: Build client
        run: npm run build --prefix client

  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install server dependencies
        run: npm install --prefix server

      - name: Install client dependencies
        run: npm install --prefix client

      - name: Deploy Server to Production
        run: npm run deploy --prefix server
        env:
            ENVIRONMENT: production

      - name: Deploy Client to Production
        run: npm run deploy --prefix client
        env:
            ENVIRONMENT: production